version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: voting_user
      POSTGRES_PASSWORD: voting_pass
      POSTGRES_DB: voting_db
    ports:
      - "5433:5432"  # Avoid conflict with other PostgreSQL instances
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: